// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Kcxyo_Bn4G65lyzpQ2Lhp2RwD7kfRZk',
    appId: '1:120437686839:web:190ed754d668aef88735b2',
    messagingSenderId: '120437686839',
    projectId: 'listaspesa-a7db9',
    authDomain: 'listaspesa-a7db9.firebaseapp.com',
    storageBucket: 'listaspesa-a7db9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxZtnNzdq9br3_aQJqJg6ghhP4Yu-q-wI',
    appId: '1:120437686839:android:b514e761d14edd208735b2',
    messagingSenderId: '120437686839',
    projectId: 'listaspesa-a7db9',
    storageBucket: 'listaspesa-a7db9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0v5Lgs2LCnsv25-qb5ih95a8Ng2-tEJg',
    appId: '1:120437686839:ios:738b2dc32cf330bd8735b2',
    messagingSenderId: '120437686839',
    projectId: 'listaspesa-a7db9',
    storageBucket: 'listaspesa-a7db9.appspot.com',
    iosClientId: '120437686839-j39cr3dep244di45sj80bc7j9r8opo5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.prova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0v5Lgs2LCnsv25-qb5ih95a8Ng2-tEJg',
    appId: '1:120437686839:ios:738b2dc32cf330bd8735b2',
    messagingSenderId: '120437686839',
    projectId: 'listaspesa-a7db9',
    storageBucket: 'listaspesa-a7db9.appspot.com',
    iosClientId: '120437686839-j39cr3dep244di45sj80bc7j9r8opo5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.prova',
  );
}
